defaults: &defaults
  # Если курс принимаемой заявки отличается от текущего более чем на этот процент,
  # то ставим новый курс
  max_incomde_diff_to_suggest: 5

  site_settings:
    extra_html: text
    order_wait_period: integer
    work_start_hm: hm
    work_finish_hm: hm

    smtp_settings_port: integer
    smtp_settings_address: string
    smtp_settings_user_name: string
    smtp_settings_password: string
    smtp_settings_authentication: string
    smtp_settings_tls: boolean
    smtp_settings_enable_starttls_auto: boolean

    mail_from: email
    support_email: email

    bot_token: string

  site_settings_defaults:
    smtp_settings_port: 465
    smtp_settings_authentication: plain
    smtp_settings_tls: true
    smtp_settings_enable_starttls_auto: true

    order_wait_period: 20
    work_start_hm: '08:00'
    work_finish_hm: '18:00'

  # Если установлено, то считаем все вознаграждения в этой валюте, если не установлено, то в валюте оригинала.
  #
  rewards_currency: USD

  # Сколько секундт курсы считать актуальными
  actual_rates:
    currency_rates_seconds: 180
    direction_rates_seconds: 180

  logo_path: /uploads/logo.svg
  max_export_records_count: 1000
  default_url_options: &default_url_options
    protocol: <%= ENV.fetch('HTTP_PROTOCOL', 'https') %>
    host: <%= ENV.fetch('LARRY_HOST', 'localhost') %>
  categories:
    system:  a8237d74-e30d-4123-8f26-eda8ba593209
    wallets: a8237d74-e30d-4123-8f26-eda8ba593208
    storno:  a8237d74-e30d-4123-8f26-eda8ba593207
    partners:  a8237d74-e30d-4123-8f26-eda8ba593206
    users: a8237d74-e30d-4123-8f26-eda8ba593205

development:
  <<: *defaults
  # Сколько секундт курсы считать актуальными
  actual_rates:
    currency_rates_seconds: 86400
    direction_rates_seconds: 86400

staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
